---

application:
  api-server-url: ${API_SERVER_URL}

server:
  port: ${PORT}

spring:
  devtools:
    restart:
      additional-paths:
        - src/main/resources/static
        - src/main/resources/templates
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths:
              - /**
      cache:
        cachecontrol:
          max-age: 31536000
          must-revalidate: true

okta:
  oauth2:
    issuer: ${OKTA_OAUTH2_ISSUER}
    client-id: ${OKTA_OAUTH2_CLIENT_ID}
    client-secret: ${OKTA_OAUTH2_CLIENT_SECRET}
    audience: ${OKTA_OAUTH2_AUDIENCE}

...
